{% set name = "xmltodict" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54306780b7c2175a3967cad1db92f218207e5bc1aba697d887807c0fb68b7649

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # https://github.com/martinblech/xmltodict/blob/v0.14.2/setup.py#L25
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - xmltodict
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/martinblech/xmltodict
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    xmltodict is a Python module that makes
    working with XML feel like you are working with JSON.
  doc_url: https://github.com/martinblech/xmltodict/blob/master/README.md
  summary: Makes working with XML feel like you are working with JSON
  dev_url: https://github.com/martinblech/xmltodict

extra:
  recipe-maintainers:
    - synapticarbors
    - ocefpaf
